### ISSUE TITLE
Errata : fib function

### ISSUE THREAD

**Issue by Fourchaux** [elzibus/The-Functional-Approach-to-Programming#1]
Yeah, "old" but crazy book.
Are you going to adapt other chapters?

Another errata:
(The printed value of fib 50 is wrong but) this code:
https://github.com/elzibus/The-Functional-Approach-to-Programming/blob/master/chap1_code.ml#L336
should be :
```
let fib n = fst(iter n (fun (x,y) ->(x+y,x)) (0,1)) ;;
```
giving:

```
fib 50 ;;
(* - : int = 12586269025 *)
```

**Comment by elzibus** [comment]
Hi ! Thanks for your comment. My plan is to go through the book, yes, as time allows..
About fib, it seems to be because the book defines the initial values as fib(0) = 1 and fib(1) = 1 ( section 1.4.6). Or am I missing something ?

**Comment by Fourchaux** [comment]
Well, testing the book function I got:
``` ocaml
fib 50 ;;
 (* - : int = 20365011074 *)

```
Checking with http://www.dcode.fr/fibonacci-numbers 
or http://www.miniwebtool.com/list-of-fibonacci-numbers/?number=60
this result is fib 51, not fib 50 . 
So...

 **Note**:  Initial values are : fib(0) = 0 and fib(1) = 1

**Comment by elzibus** [comment]
I think your note gives the reason, right ? The book says fib(0) = 1 (which is unusual).

from the miniwebtool.com site:

F0	0
....
F50	12586269025
F51	20365011074

so it looks like I am getting the F51 value one step earlier because of the different "initial conditions".

Sorry if I am missing something, I am yet to play with the code..

**Comment by Fourchaux** [comment]
Small typo:  

https://github.com/elzibus/The-Functional-Approach-to-Programming/blob/master/chap2_code.ml#L326
```
let pi = list_hom 1 ( * ) ;;

Instead of : let pi = list_hom 0 ( * ) ;;
```

**Comment by elzibus** [comment]
Thanks !

1 + 2 + 3 = 1 * 2 * 3 

... talk about using the wrong example call ... :)

**Comment by Fourchaux** [comment]
Yep. A great classic ...
