### ISSUE TITLE
MLgraph (sources and binaries)

### ISSUE THREAD

**Issue by Fourchaux** [elzibus/The-Functional-Approach-to-Programming#3]
Since you're jumping to Chap.9 (Geometry and Drawings)
(and unless you already knew it...) this link may interest you:

https://www-apr.lip6.fr/~chaillou/Public/logiciels/MLgraph/

(MLgraph program in Caml-light AND in O'Caml).

**Comment by elzibus** [comment]
Yes I saw this but I am using something else for the graphics output : I have uploaded some code that uses the nuklear GUI.
